In [1]:
# Indexing

import numpy as np

array1 = np.array([2, 3, 5, 7, 11, 13, 17, 19, 23, 29, 31])
print(array1[0])
print(array1[2])
print(array1[-1])
print(array1[-2])
print(array1[[1,3,4]])

2
5
31
29
[ 3  7 11]


In [5]:
# Indexing

array2 = np.array([2, 1, 3])
print(array1[array2])

print(array1[2:7])
print(array1[0:7])
print(array1[:7])
print(array1[2:])
print(array1[2:11:2])
print(array1[2:11:3])

[5 3 7]
[ 5  7 11 13 17]
[ 2  3  5  7 11 13 17]
[ 2  3  5  7 11 13 17]
[ 5  7 11 13 17 19 23 29 31]
[ 5 11 17 23 31]
[ 5 13 23]
