In [1]:
# Create Numpy Array
import numpy as np

arr = np.arange(1,101)
arr

array([  1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,  13,
        14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,  26,
        27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,  39,
        40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,  52,
        53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,  65,
        66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77,  78,
        79,  80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,  91,
        92,  93,  94,  95,  96,  97,  98,  99, 100])

In [1]:
# Create Numpy Array in multiples of 3
import numpy as np

arr = np.arange(3, 100, 3)
arr

array([ 3,  6,  9, 12, 15, 18, 21, 24, 27, 30, 33, 36, 39, 42, 45, 48, 51,
       54, 57, 60, 63, 66, 69, 72, 75, 78, 81, 84, 87, 90, 93, 96, 99])

In [4]:
arr1 = np.arange(10)
arr1 *2

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [5]:
arr1 + 2
arr1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [7]:
import numpy as np
array1 = np.arange(10)
array2 = np.arange(10,20)

AttributeError: module 'numpy' has no attribute 'aramge'